Synapse\Cmf\Bundle\Entity\Orm\File:
    type: entity
    repositoryClass: Synapse\Cmf\Framework\Media\File\Repository\Doctrine\DoctrineRepository
    table: synapse_file
    actAs:
        Timestampable: ~
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        storePath:
            type: string
            column: store_path
        name:
            type: string
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
