Synapse\Cmf\Bundle\Entity\Orm\Template:
    type: entity
    repositoryClass: Synapse\Cmf\Framework\Theme\Template\Repository\Doctrine\DoctrineRepository
    table: synapse_template
    actAs:
        Timestampable: ~
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    uniqueConstraints:
        content_index:
            columns: [ content_type_name, content_id, template_type_id ]
    fields:
        scope:
            type: string
        contentTypeName:
            type: string
            column: content_type_name
        contentId:
            type: string
            column: content_id
            nullable: true
        templateTypeId:
            type: string
            column: template_type_id
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    oneToMany:
        zones:
            targetEntity: Zone
            mappedBy: template
            cascade: ['persist', 'remove']
