Synapse\Cmf\Framework\Theme\Template\Entity\Template:
    group_sequence:
        - Template
        - creation
        - edition
    properties: ~
        # example:
        #     - NotBlank:
        #         groups: [creation]
